"""STEP 2 — assemble the generated files into a real, buildable project.

The Developer agents store a first draft in `generated_files`; nothing there is
runnable on its own. This module turns that draft into two build contexts (a
FastAPI backend image and a Next.js frontend image) plus a Caddy reverse-proxy
image, and a docker-compose that wires them to a per-project Postgres.

Key decisions, and why:

* **`requirements.txt` is generated here, not by the pipeline.** CONTEXT flagged
  this for Week 7: QA could import-scan and pip-install on the fly, but a deployed
  container cannot scan itself. We reuse QA's AST import scanner
  (`assembly._third_party_imports`) — the same one whose regex predecessor
  fabricated "hallucinated dependency" findings — so the manifest is derived from
  what the code actually imports, not guessed.

* **All config is baked into images; only named volumes hold data.** DevOps runs
  the build on the HOST daemon via a mounted socket (docker-out-of-docker), where
  a host *bind*-mount would resolve against the host filesystem, not the backend
  container's. Baking the Caddyfile/app into images and using named volumes for
  the database sidesteps that entirely and keeps the local and AWS paths identical.

* **The two import styles are reconciled by aliasing, not a dual PYTHONPATH** —
  reusing QA's `sitecustomize` shim (defect #4), so a mixed-style generated app
  imports each module exactly once.
"""
import os
from dataclasses import dataclass, field

from app.qa import assembly as qa

BACKEND_PORT = 8000
FRONTEND_PORT = 3000

# Always needed to run a generated FastAPI + async SQLAlchemy app, whether or not
# the code imports them by a name the scanner sees.
_BACKEND_BASE_REQS = [
    "fastapi", "uvicorn[standard]", "sqlalchemy[asyncio]", "asyncpg",
    "pydantic", "pydantic-settings", "python-dotenv",
]


@dataclass
class Manifest:
    root: str
    backend_context: str
    caddy_context: str
    app_module: str | None
    requirements: str
    has_frontend: bool
    frontend_context: str | None = None
    compose_path: str | None = None
    failures: list[str] = field(default_factory=list)


# ------------------------------------------------------------------ file split
def _is_frontend(f: dict) -> bool:
    path = (f.get("filepath") or f.get("filename") or "").lower()
    if path.startswith("frontend/"):
        return True
    if path.startswith("backend/"):
        return False
    # Fall back to extension / agent for files with an ambiguous path.
    if path.endswith((".tsx", ".ts", ".jsx", ".js", ".css", ".json")):
        return "backend" not in (f.get("agent_type") or "")
    return False


def _rel_for_backend(f: dict) -> str | None:
    """Path under the backend context's /srv, preserving the dotted module layout
    (so `backend/app/main.py` -> module `backend.app.main`)."""
    return qa._safe_relpath(f.get("filepath", ""), f.get("filename", ""))


def _rel_for_frontend(f: dict) -> str | None:
    """Path under the frontend context root, with the leading `frontend/` dropped
    so `package.json`/`app/` sit at the image root Next.js expects."""
    rel = qa._safe_relpath(f.get("filepath", ""), f.get("filename", ""))
    if rel is None:
        return None
    if rel.startswith("frontend/"):
        rel = rel[len("frontend/"):]
    return rel or None


# ------------------------------------------------------------------ manifest gen
def _backend_requirements(backend_files: list[dict]) -> str:
    wanted: set[str] = set()
    for f in backend_files:
        rel = f.get("filepath") or f.get("filename") or ""
        if not rel.endswith(".py"):
            continue
        for root in qa._third_party_imports(f.get("content") or ""):
            wanted.add(qa._PACKAGE_ALIASES.get(root, root))
    # Base set first (deduped), then the scanned extras that aren't already base.
    base_roots = {r.split("[")[0].lower() for r in _BACKEND_BASE_REQS}
    extras = sorted(p for p in wanted if p.lower() not in base_roots)
    lines = ["# Generated by DevOps from the app's actual imports (AST scan)."]
    lines += _BACKEND_BASE_REQS + extras
    # Pydantic EmailStr needs the email-validator extra, which no import names —
    # so the scan above misses it and the deployed app won't boot. Add it on use.
    if qa.needs_email_validator(f.get("content") or "" for f in backend_files) \
            and "email-validator" not in extras:
        lines.append("email-validator")
    # File/Form routes (e.g. the menu PDF upload) need python-multipart, also named
    # by no import — so the deployed app crashes at startup without it.
    if qa.needs_python_multipart(f.get("content") or "" for f in backend_files) \
            and "python-multipart" not in extras:
        lines.append("python-multipart")
    return "\n".join(lines) + "\n"


def _bootstrap_py(app_module: str) -> str:
    """Container entrypoint: create the generated schema (STEP 4), then exec
    uvicorn. Reuses QA's dual-style import discovery to find the app's Base."""
    pkg = app_module.rsplit(".", 1)[0] if "." in app_module else ""
    cands = [c for c in (pkg, "app", "backend.app") if c]
    return f'''"""DevOps bootstrap: create the generated app's schema, then serve it."""
import asyncio, importlib, os, sys

APP_MODULE = {app_module!r}
CANDS = {cands!r}


def _create_schema():
    db = None
    for c in CANDS:
        try:
            db = importlib.import_module(c + ".database")
            importlib.import_module(c + ".models")
            break
        except Exception:
            db = None
    if db is None:
        print("[devops-bootstrap] no models module found; app will manage its own schema")
        return
    eng = getattr(db, "engine", None)
    base = getattr(db, "Base", None)
    if eng is None or base is None:
        print("[devops-bootstrap] no engine/Base; skipping schema create")
        return
    try:
        async def _go():
            async with eng.begin() as conn:
                await conn.run_sync(base.metadata.create_all)
        asyncio.run(_go())
        print("[devops-bootstrap] schema created (async)")
    except Exception as e_async:
        try:
            base.metadata.create_all(bind=eng)
            print("[devops-bootstrap] schema created (sync)")
        except Exception as e_sync:
            print("[devops-bootstrap] schema create skipped:", e_async, e_sync)


_create_schema()
os.execvp("uvicorn", ["uvicorn", APP_MODULE + ":app",
                      "--host", "0.0.0.0", "--port", "{BACKEND_PORT}"])
'''


def _backend_dockerfile() -> str:
    return f'''FROM python:3.12-slim
WORKDIR /srv
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=/srv
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY srv/ /srv/
EXPOSE {BACKEND_PORT}
# Secrets are injected at RUN time via --env-file, never baked into these layers.
CMD ["python", "/srv/_devops_bootstrap.py"]
'''


def _frontend_dockerfile() -> str:
    # Build at image-build time so a broken generated UI fails the deploy honestly
    # (rather than crash-looping at runtime).
    return f'''FROM node:20-slim
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE {FRONTEND_PORT}
CMD ["npm", "run", "start"]
'''


def _caddyfile(subdomain: str, has_frontend: bool, local: bool,
               le_email: str) -> str:
    """Reverse proxy. `/api/*` + the app's own health/openapi go to the backend;
    everything else to the frontend (or the backend if there is no frontend)."""
    web = "backend:8000" if not has_frontend else "frontend:3000"
    api_matcher = "@api path /api/* /openapi.json /docs /health /healthz"
    if local:
        # Local: an internally-trusted cert. The site MUST name the hosts it will
        # be reached by, or `tls internal` has no hostname to mint a cert for and
        # the TLS handshake fails with an internal-error alert. `localhost` is for
        # the user's browser; `host.docker.internal` is how the in-container health
        # probe reaches the host-published port on Docker Desktop.
        # ssl_type is recorded as 'self_signed_local', never lets_encrypt.
        return f'''{{
	auto_https disable_redirects
}}
localhost, host.docker.internal {{
	tls internal
	{api_matcher}
	handle @api {{
		reverse_proxy backend:8000
	}}
	handle {{
		reverse_proxy {web}
	}}
}}
'''
    # AWS: real Let's Encrypt for the real subdomain.
    return f'''{{
	email {le_email}
}}
{subdomain} {{
	{api_matcher}
	handle @api {{
		reverse_proxy backend:8000
	}}
	handle {{
		reverse_proxy {web}
	}}
}}
'''


def _caddy_dockerfile() -> str:
    return '''FROM caddy:2
COPY Caddyfile /etc/caddy/Caddyfile
'''


def _compose(names: dict, has_frontend: bool, https_host_port: int,
             http_host_port: int, subdomain: str, *, use_images: bool,
             image_refs: dict | None = None) -> str:
    """docker-compose for one isolated app. `use_images=False` builds locally;
    `use_images=True` references pushed images (the AWS/EC2 path)."""
    image_refs = image_refs or {}
    db_url = (f"postgresql+asyncpg://{names['db_user']}:{names['db_password']}"
              f"@db:5432/{names['db_name']}")

    def _svc_source(kind: str, context: str) -> str:
        if use_images:
            return f"    image: {image_refs.get(kind)}"
        return f"    build: ./{context}"

    frontend_block = ""
    if has_frontend:
        frontend_block = f'''  frontend:
{_svc_source('frontend', 'frontend')}
    container_name: {names['frontend_container']}
    environment:
      NEXT_PUBLIC_API_URL: "https://{subdomain}/api"
    depends_on:
      - backend
    networks: [appnet]
    restart: unless-stopped
'''

    return f'''# DevOps-generated deployment for project {names['project_id']} — ISOLATED:
# its own network, its own database + credentials, its own containers. No name
# here is shared with any other project (all derived from project_id).
name: {names['compose_project']}

services:
  db:
    image: postgres:16-alpine
    container_name: {names['db_container']}
    environment:
      POSTGRES_DB: {names['db_name']}
      POSTGRES_USER: {names['db_user']}
      POSTGRES_PASSWORD: {names['db_password']}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [appnet]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {names['db_user']} -d {names['db_name']}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
{_svc_source('backend', 'backend')}
    container_name: {names['backend_container']}
    # DATABASE_URL is safe to inline (per-project, internal); real SECRETS come
    # from the 0600 --env-file the driver passes, never from this file.
    environment:
      DATABASE_URL: "{db_url}"
    env_file:
      - deploy.env
    depends_on:
      db:
        condition: service_healthy
    networks: [appnet]
    restart: unless-stopped

{frontend_block}  caddy:
{_svc_source('caddy', 'caddy')}
    container_name: {names['caddy_container']}
    ports:
      - "{http_host_port}:80"
      - "{https_host_port}:443"
    depends_on:
      - backend
    networks: [appnet]
    restart: unless-stopped

networks:
  appnet:
    name: {names['network']}

volumes:
  dbdata:
    name: {names['db_volume']}
'''


# ------------------------------------------------------------------ entrypoint
def build(files: list[dict], root: str, names: dict, *, subdomain: str,
          has_frontend_override: bool | None = None, local: bool = True,
          le_email: str = "", https_host_port: int = 443,
          http_host_port: int = 80, use_images: bool = False,
          image_refs: dict | None = None) -> Manifest:
    """Write every build context + the compose file under `root`. Never raises —
    problems are returned as `Manifest.failures` (the QA-agent convention)."""
    failures: list[str] = []
    backend_files = [f for f in files if not _is_frontend(f)]
    frontend_files = [f for f in files if _is_frontend(f)]
    has_frontend = (has_frontend_override
                    if has_frontend_override is not None
                    else bool(frontend_files))

    # ---- backend context: /srv/<module layout> + requirements + bootstrap ----
    backend_ctx = os.path.join(root, "backend")
    srv = os.path.join(backend_ctx, "srv")
    os.makedirs(srv, exist_ok=True)
    written: dict[str, str] = {}
    for f in backend_files:
        rel = _rel_for_backend(f)
        if rel is None:
            failures.append(f"unsafe backend path: {f.get('filepath')!r}")
            continue
        dest = os.path.join(srv, rel)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(f.get("content") or "")
        written[rel] = f.get("content") or ""

    # __init__.py for every python package dir (import cleanliness).
    for rel in list(written):
        if rel.endswith(".py"):
            parts = rel.split("/")[:-1]
            for i in range(len(parts)):
                pkg = os.path.join(srv, *parts[: i + 1], "__init__.py")
                if not os.path.exists(pkg):
                    os.makedirs(os.path.dirname(pkg), exist_ok=True)
                    open(pkg, "w").close()

    app_module = qa._find_app_module(written)
    if app_module is None:
        failures.append(
            "no FastAPI entrypoint found in the generated backend (no file "
            "creates a FastAPI app) — cannot build a runnable backend image."
        )
        # Still write what we can so the failure is inspectable.
        app_module = "backend.app.main"

    # Reuse QA's alias shim so `app.*` and `backend.app.*` are one module object.
    qa._write_alias_hook(srv, app_module)

    with open(os.path.join(srv, "_devops_bootstrap.py"), "w", encoding="utf-8") as fh:
        fh.write(_bootstrap_py(app_module))
    requirements = _backend_requirements(backend_files)
    with open(os.path.join(backend_ctx, "requirements.txt"), "w", encoding="utf-8") as fh:
        fh.write(requirements)
    with open(os.path.join(backend_ctx, "Dockerfile"), "w", encoding="utf-8") as fh:
        fh.write(_backend_dockerfile())

    # ---- frontend context ----
    frontend_ctx = None
    if has_frontend:
        frontend_ctx = os.path.join(root, "frontend")
        os.makedirs(frontend_ctx, exist_ok=True)
        saw_pkg = False
        for f in frontend_files:
            rel = _rel_for_frontend(f)
            if rel is None:
                failures.append(f"unsafe frontend path: {f.get('filepath')!r}")
                continue
            if rel == "package.json":
                saw_pkg = True
            dest = os.path.join(frontend_ctx, rel)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(f.get("content") or "")
        with open(os.path.join(frontend_ctx, "Dockerfile"), "w", encoding="utf-8") as fh:
            fh.write(_frontend_dockerfile())
        if not saw_pkg:
            failures.append(
                "frontend has no package.json — cannot build a Next.js image. "
                "(Same gap QA's Step 5 hit; the Architect commissions FND-3.)"
            )

    # ---- caddy context ----
    caddy_ctx = os.path.join(root, "caddy")
    os.makedirs(caddy_ctx, exist_ok=True)
    with open(os.path.join(caddy_ctx, "Caddyfile"), "w", encoding="utf-8") as fh:
        fh.write(_caddyfile(subdomain, has_frontend, local, le_email))
    with open(os.path.join(caddy_ctx, "Dockerfile"), "w", encoding="utf-8") as fh:
        fh.write(_caddy_dockerfile())

    # ---- compose ----
    compose_path = os.path.join(root, "docker-compose.deploy.yml")
    with open(compose_path, "w", encoding="utf-8") as fh:
        fh.write(_compose(names, has_frontend, https_host_port, http_host_port,
                          subdomain, use_images=use_images, image_refs=image_refs))

    return Manifest(
        root=root,
        backend_context=backend_ctx,
        caddy_context=caddy_ctx,
        frontend_context=frontend_ctx,
        app_module=app_module,
        requirements=requirements,
        has_frontend=has_frontend,
        compose_path=compose_path,
        failures=failures,
    )
