"""Step-6 proof: every provider path really captures a real token count.

The bar here is deliberately higher than "the code compiles and the column
exists". Per the standing principle in CONTEXT.md, a counter that never
increments also reports a number under budget — so instrumentation is not done
until each extraction path has been shown to move a number into the database.

WHY MOCKED RATHER THAN REAL CALLS. Two reasons, and the second is the important
one:
  1. Zero spend.
  2. A real call returns an unknown token count, so the only assertable property
     would be "nonzero" — which a hardcoded constant would satisfy just as well.
     A mocked response has a KNOWN ground truth, so we can assert the exact
     numbers and catch an extraction that reads the wrong field. Each provider
     gets deliberately asymmetric prompt/completion values so a swapped pair
     fails loudly instead of averaging out.

The real `anthropic` / `google.generativeai` / `openai` modules are installed, so
their genuine import statements inside codegen._via_* are exercised; only the
network client is replaced.

NEGATIVE CONTROL is the point of scenario N. A provider response carrying no
usage block MUST land as capture_ok=false with NULL tokens — never 0. That is
what makes the positive assertions meaningful: it proves the capture path can
actually fail, rather than always producing a reassuring number.

Zero LLM spend. Run:
  docker compose run --rm --no-deps -e PYTHONPATH=/app -v "$PWD/backend:/app" \
      backend python tests/test_token_instrumentation.py
"""
import asyncio
import sys
import uuid

from sqlalchemy import delete, select

import app.codegen as codegen
from app import usage
from app.config import settings
from app.database import async_session
from app.models import LLMUsage, Project

_failures: list[str] = []
RUN_ID = f"step6-proof-{uuid.uuid4().hex[:8]}"
MARKER = "SYNTHETIC-STEP6"
# llm_usage.project_id is a real FK to projects. The first version of this test
# used a fabricated id and every insert was rejected — which usage.record()
# swallowed by design, so the run "succeeded" with zero rows written. Use a real
# project row instead.
PROJECT_ID: int = 0


def check(label: str, cond: bool, detail: str = "") -> None:
    print(f"  [{'PASS' if cond else 'FAIL'}] {label}" + (f"   ({detail})" if detail else ""))
    if not cond:
        _failures.append(label)


# ------------------------------------------------------------- fake responses
class _Obj:
    def __init__(self, **kw):
        self.__dict__.update(kw)


def openai_response(prompt=None, completion=None):
    """Shape: resp.choices[0].message.content, resp.usage.prompt_tokens/..."""
    usage_obj = None
    if prompt is not None:
        usage_obj = _Obj(prompt_tokens=prompt, completion_tokens=completion,
                         total_tokens=prompt + completion)
    return _Obj(choices=[_Obj(message=_Obj(content="generated by openai"))],
                usage=usage_obj)


def anthropic_response(prompt=None, completion=None):
    """Shape: resp.content[] text blocks, resp.usage.input_tokens/output_tokens."""
    usage_obj = None
    if prompt is not None:
        usage_obj = _Obj(input_tokens=prompt, output_tokens=completion)
    return _Obj(content=[_Obj(type="text", text="generated by anthropic")],
                usage=usage_obj)


def google_response(prompt=None, completion=None):
    """Shape: resp.text, resp.usage_metadata.prompt_token_count/..."""
    meta = None
    if prompt is not None:
        meta = _Obj(prompt_token_count=prompt, candidates_token_count=completion,
                    total_token_count=prompt + completion)
    return _Obj(text="generated by gemini", usage_metadata=meta)


# ------------------------------------------------------------------- patching
def patch_openai(resp):
    async def _create(**kw):
        return resp
    codegen._openai = _Obj(chat=_Obj(completions=_Obj(create=_create)))


def patch_anthropic(resp):
    import anthropic

    class _FakeClient:
        def __init__(self, **kw):
            self.messages = _Obj(create=self._create)

        async def _create(self, **kw):
            return resp

    anthropic.AsyncAnthropic = _FakeClient
    settings.anthropic_api_key = "test-key-not-real"


def patch_google(resp):
    import google.generativeai as genai

    class _FakeModel:
        def __init__(self, *a, **kw):
            pass

        async def generate_content_async(self, *a, **kw):
            return resp

    genai.configure = lambda **kw: None
    genai.GenerativeModel = _FakeModel
    settings.gemini_api_key = "test-key-not-real"


async def latest_row() -> LLMUsage | None:
    async with async_session() as db:
        return (await db.execute(
            select(LLMUsage).where(LLMUsage.run_id == RUN_ID)
            .order_by(LLMUsage.id.desc()).limit(1)
        )).scalars().first()


# ==================================================== per-provider capture proof
async def prove(provider_label: str, model: str, patcher, responder,
                prompt: int, completion: int, expect_model: str,
                expect_priced: bool):
    print(f"\n=== {provider_label}: real capture, known ground truth "
          f"({prompt} prompt / {completion} completion) ===")
    patcher(responder(prompt, completion))

    text, model_used = await codegen.generate(model, "sys", "user", temperature=0.1)
    row = await latest_row()

    print(f"    generate() -> text={text!r}, model_used={model_used!r}")
    if row is None:
        check(f"{provider_label}: a usage row was written", False,
              "no row found — nothing was captured")
        return
    print(f"    llm_usage row: provider={row.provider} model_used={row.model_used} "
          f"prompt={row.prompt_tokens} completion={row.completion_tokens} "
          f"total={row.total_tokens} cost={row.cost_usd} "
          f"capture_ok={row.capture_ok}")

    check(f"{provider_label}: a usage row was written", True)
    check(f"{provider_label}: capture_ok is true", row.capture_ok is True)
    check(f"{provider_label}: prompt_tokens is the REPORTED number, not 0",
          row.prompt_tokens == prompt, f"got {row.prompt_tokens}, expected {prompt}")
    check(f"{provider_label}: completion_tokens is the REPORTED number, not 0",
          row.completion_tokens == completion,
          f"got {row.completion_tokens}, expected {completion}")
    check(f"{provider_label}: prompt and completion were not swapped",
          row.prompt_tokens != row.completion_tokens
          and row.prompt_tokens == prompt)
    check(f"{provider_label}: total_tokens is the sum",
          row.total_tokens == prompt + completion, str(row.total_tokens))
    check(f"{provider_label}: provider recorded correctly",
          row.provider == provider_label, row.provider)
    check(f"{provider_label}: concrete billed model id recorded",
          row.model_used == expect_model, f"got {row.model_used}, want {expect_model}")
    check(f"{provider_label}: attributed to the run via run_id",
          row.run_id == RUN_ID, str(row.run_id))
    check(f"{provider_label}: attributed to the project and stage",
          row.project_id == PROJECT_ID and row.stage == "qa",
          f"project_id={row.project_id} stage={row.stage}")

    if expect_priced:
        expected = usage.price(expect_model, prompt, completion)
        check(f"{provider_label}: cost computed from a CONFIRMED rate (nonzero)",
              row.cost_usd is not None and float(row.cost_usd) > 0
              and abs(float(row.cost_usd) - expected) < 1e-9,
              f"got {row.cost_usd}, expected {expected}")
    else:
        check(f"{provider_label}: cost is NULL (rate not confirmed), tokens kept",
              row.cost_usd is None and row.total_tokens > 0,
              f"cost={row.cost_usd} total={row.total_tokens}")


# ============================================ NEGATIVE CONTROL — must be visible
async def prove_capture_failure_is_visible():
    print("\n=== N: provider returns NO usage block — must be UNKNOWN, never 0 ===")
    for label, model, patcher, responder in (
        ("openai", "gpt-4o", patch_openai, openai_response),
        ("anthropic", "claude-sonnet", patch_anthropic, anthropic_response),
        ("google", "gemini-2.5-flash-lite", patch_google, google_response),
    ):
        patcher(responder(None, None))       # response with usage stripped out
        await codegen.generate(model, "sys", "user")
        row = await latest_row()
        if row is None:
            check(f"{label}: a row is still written when capture fails", False,
                  "no row — a failed capture vanished entirely")
            continue
        print(f"    {label}: capture_ok={row.capture_ok} prompt={row.prompt_tokens} "
              f"completion={row.completion_tokens} total={row.total_tokens} "
              f"cost={row.cost_usd}")
        check(f"{label}: a row is still written when capture fails", True)
        check(f"{label}: capture_ok is FALSE", row.capture_ok is False)
        check(f"{label}: tokens are NULL, NOT 0 (0 would read as a free call)",
              row.prompt_tokens is None and row.completion_tokens is None
              and row.total_tokens is None,
              f"prompt={row.prompt_tokens} completion={row.completion_tokens}")
        check(f"{label}: cost is NULL when tokens are unknown", row.cost_usd is None)


# ============================== every model the router can pick must price
async def prove_every_routed_model_prices():
    print("\n=== P: every model routing can choose has a confirmed rate ===")
    # Concrete billed ids — what _via_* actually passes to usage.price() — with
    # the published per-MTok rates. 1M in + 1M out makes the expected cost
    # exactly the two rates summed, so the arithmetic is checkable by hand.
    expected = {
        "gpt-4o": (2.50, 10.00),
        "gpt-4o-mini": (0.15, 0.60),
        "claude-sonnet-5": (2.00, 10.00),
        "claude-opus-4-8": (5.00, 25.00),
        "gemini-flash-lite-latest": (0.10, 0.40),
    }
    for model, (rin, rout) in expected.items():
        cost = usage.price(model, 1_000_000, 1_000_000)
        print(f"    {model:26} 1M in + 1M out -> ${cost}")
        check(f"{model}: prices to a real number, not NULL", cost is not None)
        check(f"{model}: cost is nonzero", bool(cost))
        check(f"{model}: arithmetic matches the published rate",
              cost is not None and abs(cost - (rin + rout)) < 1e-9,
              f"got {cost}, expected {rin + rout}")

    # The split that actually drives unit economics: Opus reviews every file and
    # ignores CODEGEN_MODE by design, so it dominates spend.
    opus = usage.price("claude-opus-4-8", 1_000_000, 1_000_000)
    flash = usage.price("gemini-flash-lite-latest", 1_000_000, 1_000_000)
    check("Opus is an order of magnitude dearer than Flash-Lite (sanity)",
          opus is not None and flash is not None and opus > flash * 10,
          f"opus=${opus} vs flash=${flash}")

    stale = usage.stale_rates()
    check("no promotional rate has silently expired", not stale,
          f"EXPIRED {stale}: re-confirm and update app/usage._PRICING, then "
          f"update or remove the _RATE_EXPIRY entry" if stale else "")
    # Prove the tripwire can FIRE, rather than trusting that it would. A staleness
    # check that never triggers is exactly the pattern this suite exists to catch.
    check("the expiry tripwire actually fires once the date passes",
          usage.stale_rates(today="2099-01-01") == ["claude-sonnet-5"],
          str(usage.stale_rates(today="2099-01-01")))
    print(f"    time-bound rates: {usage._RATE_EXPIRY} — stale today: {stale or 'none'}")


# ================================================== aggregate + honesty of totals
async def prove_totals_flag_incompleteness():
    print("\n=== A: a run's total must be able to say it is incomplete ===")
    async with async_session() as db:
        rows = (await db.execute(
            select(LLMUsage).where(LLMUsage.run_id == RUN_ID)
        )).scalars().all()

    captured = [r for r in rows if r.capture_ok]
    missing = [r for r in rows if not r.capture_ok]
    total_tokens = sum(r.total_tokens or 0 for r in captured)
    priced = [r for r in captured if r.cost_usd is not None]
    total_cost = sum(float(r.cost_usd) for r in priced)

    print(f"    rows={len(rows)}  captured={len(captured)}  "
          f"capture_failed={len(missing)}")
    print(f"    total tokens (captured rows only) = {total_tokens}")
    print(f"    total cost (priced rows only)     = ${total_cost:.8f} "
          f"across {len(priced)} of {len(captured)} captured rows")

    check("both captured and capture-failed rows exist in this run",
          len(captured) >= 3 and len(missing) >= 3,
          f"captured={len(captured)} missing={len(missing)}")
    check("the aggregate can distinguish 'no spend' from 'not measured'",
          len(missing) > 0 and total_tokens > 0)
    check("run_id joins usage to the QA pass that spent it",
          all(r.run_id == RUN_ID for r in rows))


async def cleanup() -> int:
    async with async_session() as db:
        n = len((await db.execute(
            select(LLMUsage.id).where(LLMUsage.run_id == RUN_ID))).all())
        await db.execute(delete(LLMUsage).where(LLMUsage.run_id == RUN_ID))
        await db.execute(delete(Project).where(Project.prompt.like(f"{MARKER}%")))
        await db.commit()
    return n


async def main():
    global PROJECT_ID
    # CODEGEN_MODE=cheap would silently reroute every model to the budget one and
    # make the per-provider assertions test the same path three times.
    settings.codegen_mode = "real"

    await cleanup()
    async with async_session() as db:
        p = Project(prompt=f"{MARKER}: token instrumentation proof", status="secured")
        db.add(p)
        await db.commit()
        await db.refresh(p)
        PROJECT_ID = p.id
    print(f"(synthetic project {PROJECT_ID}, run_id {RUN_ID})")

    token = usage.set_run_context(run_id=RUN_ID, project_id=PROJECT_ID, stage="qa")
    try:
        await prove("openai", "gpt-4o", patch_openai, openai_response,
                    1234, 567, expect_model="gpt-4o", expect_priced=True)
        await prove("anthropic", "claude-sonnet", patch_anthropic, anthropic_response,
                    2345, 678, expect_model="claude-sonnet-5", expect_priced=True)
        await prove("google", "gemini-2.5-flash-lite", patch_google, google_response,
                    3456, 789, expect_model="gemini-flash-lite-latest",
                    expect_priced=True)
        await prove_capture_failure_is_visible()
        await prove_every_routed_model_prices()
        await prove_totals_flag_incompleteness()
    finally:
        usage.reset_run_context(token)
        removed = await cleanup()
        print(f"\n(cleaned {removed} synthetic usage row(s))")

    print("\n" + "=" * 64)
    if _failures:
        print(f"RESULT: {len(_failures)} check(s) FAILED:")
        for f in _failures:
            print(f"   - {f}")
        sys.exit(1)
    print("RESULT: ALL CHECKS PASSED ✓")


if __name__ == "__main__":
    asyncio.run(main())
